### ISSUE TITLE
Support parsing 5-digit POTA reference numbers

### ISSUE THREAD

**Issue by thomasrussellmurphy** [on4kjm/FLEcli#105]
POTA references are now [Prefix]-[4 or 5 digits], starting with K (USA): https://pota.app/#/park/K-10000

Current `load` result: `Parsing error at line 18: Unable to make sense of [k-12345].`

**Comment by thomasrussellmurphy** [comment]
It looks like the only change is to update this regex: https://github.com/on4kjm/FLEcli/blob/9f0664d0caff81b005cd6b319f9e784d87f35a34/fleprocess/validate.go#L54

**Comment by szhayes** [comment]
Second this request please.

**Comment by k0emt** [comment]
I will work on getting the build actions functional on my fork next week.

**Comment by k0emt** [comment]
Saw what you were saying and corrected it.  If you were thinking of other wording, it is fine with me if you make a change on the branch.

**Comment by jmMeessen** [comment]
Perfect. Thank you.
Cutting a release right now

**Comment by jmMeessen** [comment]
@k0emt , @szhayes , @thomasrussellmurphy 

Release v0.1.6 is now available on GitHub and HomeBrew.

Thank you for your patience.

**Comment by thomasrussellmurphy** [comment]
Thanks! Ticket is also open for [MacPorts](https://trac.macports.org/ticket/68692).
