### ISSUE TITLE
Support for POTA prefix ending with a digit

### ISSUE THREAD

**Issue by yu3fms** [on4kjm/FLEcli#108]
Hi all, right now FLECli throws error when parsing a pota reference whose prefix ends with a digit.

Processing errors:
Parsing error at line 7: Unable to make sense of [HB0-0005].
Parsing error at line 8: Unable to make sense of [E7-0005].
Parsing error at line 9: Unable to make sense of [T9-0005].

So the line at
https://github.com/on4kjm/FLEcli/blob/9f0664d0caff81b005cd6b319f9e784d87f35a34/fleprocess/validate.go#L54

should be
var validPotaRegexp = regexp.MustCompile(`^[\d]{0,1}[A-Z]{1,2}[\d]{0,1}-[\d]{4,5}$`)

Rebuild with this change solves the issue.
Someone with better knowledge of go regex then mine should look into this.

**Comment by jmMeessen** [comment]
Thank you for reporting this issue, OM.

Could someone more active than me in POTA activations, point me to the official reference rules documentation? Could maybe kill several flies in one clap.

**Comment by jmMeessen** [comment]
fixed and released v0.1.7 , @yu3fms

**Comment by jmMeessen** [comment]
FYI @thomasrussellmurphy if your want to do your Macports magic...

**Comment by yu3fms** [comment]
Smooth man, thanks!

**Comment by thomasrussellmurphy** [comment]
I've updated my request on the MacPorts side. Thanks for the updates!

**Comment by yu3fms** [comment]
> Thank you for reporting this issue, OM.
> 
> Could someone more active than me in POTA activations, point me to the official reference rules documentation? Could maybe kill several flies in one clap.

Sorry for late response. Rules and docs are officially on https://docs.pota.app
I have received list of all the current active unique park references. I will take time this weekend to make a dummy txt file with this data and run a FLECli through it and I will report back with everything.

**Comment by w1mt** [comment]
Looks like the prefix can be very varied. Look at Sovereign Military Order of Malta for instance 1A0KM is the prefix. The regex to contain all the possibilities is going to be a very complicated object.

**Comment by yu3fms** [comment]
Heh, indeed the test has not passed with one error.
Here are the files:

[pota_prefix_test_log.txt](https://github.com/on4kjm/FLEcli/files/13510771/pota_prefix_test_log.txt)
[flecli_pota_test_log_output.txt](https://github.com/on4kjm/FLEcli/files/13510775/flecli_pota_test_log_output.txt)

**Comment by jmMeessen** [comment]
Thank you very much for your interest and providing me test  data.
I propose to open a new issue (#111) to improve(and finalize) the POTA reference . This will help to keep things tidy (I am experimenting with changelog generation).

**Comment by jmMeessen** [comment]
@w1mt , @thomasrussellmurphy : FYI

**Comment by yu3fms** [comment]
Thank you for writing this fine piece :) K, we'll move the discussion to #111
