### ISSUE TITLE
Can POTA data be added?

### ISSUE THREAD

**Issue by rsuzuki0** [on4kjm/FLEcli#69]
Parks on the air log format is virtually the same as WWFF but some formats are different.  For example, the US park references are K-NNNN in POTA where KFF-NNNN in WWFF. Uses of SIG_INFO, MY_SIG_INFO, etc. are parallel/analogous. Can --pota -p switches be added with these minor adjustments?

**Comment by rsuzuki0** [comment]
For now, the POTA park reference can be set as if they are/were WWFF reference in the log file:
mywwff kff-0802

Then run this:
sed -e 's/WWFF/POTA/' -e 's/MY_SIG_INFO:8>KFF/MY_SIG_INFO:6>K/' WWFF_ADIF_FILE > POTA_ADIF_FILE

But it would be super nice if we could also specify
mypota k-0802
in the input file and the output ADIF format controlled by the commandline switch...

**Comment by jmMeessen** [comment]
Hello @rsuzuki0 

Thank you for your interest in this and sharing this excellent enhancement idea. Do you have, by any chance, a link to the required POTA output file specification?

Are you a mac user? I planned to add Brew as a distribution vector. If yes, I could provide both features in the next release

I will get back into this in the coming days.

73 de ON4KJM

**Comment by rsuzuki0** [comment]
I find this page informative: http://morsel.info/?page_id=852
More clarification can be obtained from one of the POTA people. Their official documentation doesn't seem to go in full details.

Yes, I'm a Mac user. Brew would be nice, especially if it solves the unsigned warning, but I'm also ok with github distribution as-is.

**Comment by rsuzuki0** [comment]
Another ref:
https://groups.io/g/N3FJPSoftwareUsers/topic/logging_for_pota/34505762?p=

**Comment by rsuzuki0** [comment]
Thank you for your work. I just generated six ADIF files for my activations and sent them to the log manager. Hope they don't find any problem but will report back.

**Comment by rsuzuki0** [comment]
I've been submitting my activation log to the area log manager and there has not been a complaint. So this seems working fine. Thank you!

By the way, I've been using a simple Makefile in the folder I generate ADIF files:

FLE     =       /whatever/FLEcli/FLEcli
FLEFLAGS        =       adif -i --overwrite --pota

%.adi: %.txt
        $(FLE) $(FLEFLAGS) $<


ALL:    *.adi

merge:  *.adi
        rm -rf ALL.adif
        adif_merge --output ALL.adif *.adi

ls:
        ls -lt *.txt *.adi

clean:
        rm -f *~
