### ISSUE TITLE
Using a tab to delimit some keyword lines causes error

### ISSUE THREAD

**Issue by rsuzuki0** [on4kjm/FLEcli#70]
Lines for keywords date, mywwff, mygrid, mycall, operator causes an error. The error messages make little sense like:
> Fatal error at line 3: Gap start time is empty
> Parsing error at line 4: Unable to make sense of [mywwff]. Unable to make sense of [kff-0802].
> Parsing error at line 6: Unable to make sense of [Mygrid].
> Fatal error: missing new time to infer time

But once the tabs on those lines are replaced with one or more spaces, these errors vanish.

Tabs in QSO lines and freq/mode lines seem to work fine.

**Comment by jmMeessen** [comment]
Good observation, @rsuzuki0 !

I will look into this.

**Comment by jmMeessen** [comment]
To be sure to fix this issue correctly @rsuzuki0 , could you provide me a sample file ?

**Comment by rsuzuki0** [comment]
This error is fairly predictable, just use a tab as a delimiter in one of the "preamble" lines and the error will happen in some forms.

[Testlog.txt](https://github.com/on4kjm/FLEcli/files/7619738/Testlog.txt)

In this example, I made the mygrid line delimited by a tab and causes an error.

Processing errors:
Parsing error at line 6: Unable to make sense of [Mygrid].

**Comment by jmMeessen** [comment]
Thanks for the test log. I was able to spot where the bug lives.

**Comment by rsuzuki0** [comment]
0.1.4 seems to work fb hr.
