### ISSUE TITLE
S2S contacts not recognized properly

### ISSUE THREAD

**Issue by jmMeessen** [on4kjm/FLEcli#78]
Hello Jean-Marc,

I really love FLE and was very happy to find your FLEcli since I do not use Windows computers. I downloaded FLEcli_0.1.4_macOS_arm64.tar.gz since I have a Mac with M1 processor. I entered a SOTA log in FLE format and process it with FLEcli, but there is a bug. I ran the same log file via FLE 2.12 and it works as expected so the format of my log file is correct. The problem is that FLEcli is not properly recognizing S2S contacts - it puts the SOTA REF instead of the callsign:

Here is beginning of log file:
```
mycall wu7h
mysota w7w/cw-064
date 2022-03-12
20m ssb
1730 K7EEX w0c/fr-058
35 kg7azy w7a/yv-102
37 12m cw na6mg w6/ct-262
45 20m ssb w6wss w6/sd-108
46 2m fm k7jro
1804 20m cw kr7rk w7a/cs-032
```

Here is output:

```
./FLEcli csv 03-12-2022-cw-064.log --overwrite
No output provided, defaulting to “03-12-2022-cw-064.csv”
MyCall WU7H
MySOTA W7W/CW-064

Date Time Band Mode Call Sent Rcvd Notes

2022-03-12 1730 20m SSB W0C/FR-058 59 59 [s2s]
2022-03-12 1735 20m SSB W7A/YV-102 59 59
2022-03-12 1737 12m CW NA6MG 599 599 W6/CT-262
2022-03-12 1745 20m SSB W6WSS 59 59 [s2s] W6/SD-108
2022-03-12 1746 2m FM K7JRO 59 59
2022-03-12 1804 20m CW W7A/CS-032 599 599 [s2s]
```

I also tried the ‘sota’ keyword before the REF and it did not help.

Thank you for your great work on this VERY useful program!

73,

-Josh WU7H

**Comment by jmMeessen** [comment]
The issue is identified: the "american" SOTA reference is parsed as a call sign and not as ref. 
Test included to reproduce the issue.

**Comment by jmMeessen** [comment]
delivered.

**Comment by rexington** [comment]
Wow! That was fast. Thanks for all the work you've put into this app!
