### ISSUE TITLE
Setting Coordinates and MY_CNTY in ADIF output

### ISSUE THREAD

**Issue by rsuzuki0** [on4kjm/FLEcli#80]
Mygrid is used to set up the station's grid square, and that info is included in each line of ADIF. Can we do the same thing for MY_CNTY, MY_LAT, and MY_LON? The original FLE may or may not implement it, but these are important for a lot of portable operators.

**Comment by nicheath** [comment]
I added MY_CNTY support in this PR.
https://github.com/on4kjm/FLEcli/pull/128

**Comment by nicheath** [comment]
I added MY_LAT and MY_LON support in this PR.
https://github.com/on4kjm/FLEcli/pull/129

**Comment by nicheath** [comment]
Both of these changes are available for you to build from my fork branch mymaster.

**Comment by jmMeessen** [comment]
Thanks a lot for these PRs @nicheath . I will review them as soon as possible

**Comment by jmMeessen** [comment]
Merged #128
